clear; clc;

% Add current directory and all subdirectories to path
addpath(pwd, ...
    fullfile(pwd, 'simulation'), ...
    fullfile(pwd, 'passengers'), ...
    fullfile(pwd, 'boarding'), ...
    fullfile(pwd, 'visualization'), ...
    fullfile(pwd, 'utils'));

params = load_params();

options = struct('verbose', true, 'enable_pauses', params.show_visu);
KPI = run_simulation(params, options);
